apiVersion: v1
kind: ConfigMap
metadata:
    name: kiali
    labels:
        app: kiali
        chart: kiali
        heritage: Tiller
        release: istio
data:
    config.yaml: |
        istio_namespace: istio-system
        auth:
          strategy: "login"
        server:
          port: 20001
          web_root: /kiali
        external_services:
          tracing:
            url: http://jaeger-query:16686/jaeger
          grafana:
            url: http://grafana:3000
          prometheus:
            url: http://prometheus:9090
